### ISSUE TITLE
This tool worked great for me, thank you!

### ISSUE THREAD

**Issue by virtuald** [stnuessl/rf#1]
Compiled it against clang 6 as distributed in Ubuntu 18.04, had to comment out the version display, but other than that it worked like a charm.

**Comment by stnuessl** [comment]
That's so cool. 
As the project is not being maintained for some time now and the clang libraries being a little bit famous for breaking their APIs with new major releases, I didn't expect someone to use this tool at all. It's also great to hear that it worked - I'm always a little bit
skeptical about the correctness. 
Thank you for letting me know.
